project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R - KNBS"
  author: "Menna Bishop, Christopher Steinberg"
  date: "4/12/2025"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
      - basics.qmd
      - data_manipulation.qmd
      - importing_data.qmd
      - ggplot.qmd
    - part: applications.qmd
      chapters:
      - application_1.qmd
    - part: mapping.qmd
      #chapters:
      #- spatial_operations.qmd

format:
  html:
    theme: cosmo

editor: visual

