project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R - KNBS"
  author: "Menna Bishop, Christopher Steinberg"
  date: "4/12/2025"
  chapters:
    - index.qmd
    - data_manipulation.qmd
    - importing_data.qmd
    - ggplot.qmd
    #- intro_to_gis_in_r.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

